version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"     # Cá»•ng AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
      
  user:
    build: ./be/shopquanaobe
    env_file:
      - ./be/shopquanaobe/.env
    container_name: shopquanaobe
    ports:
      - "3004:3000"  # Container: 3000, Host: 3004
    environment:
      - PORT=3000
    volumes:
      - ./be/shopquanaobe:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    networks:
      - app-network

  product:
    build: ./be/mcrproduct/mcrproduct
    env_file:
      - ./be/mcrproduct/mcrproduct/.env
    container_name: mcrproduct
    ports:
      - "3002:3000"  # Container: 3000, Host: 3002
    environment:
      - PORT=3000
    volumes:
      - ./be/mcrproduct/mcrproduct:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    networks:
      - app-network

  cloundinary:
    build:
      context: ./be/mcrcloundinary/mcrcloundinary
    env_file:
      - ./be/mcrcloundinary/mcrcloundinary/.env
    container_name: mcrcloundinary
    ports:
      - "3003:3000"  # Container: 3000, Host: 3003
    environment:
      - PORT=3000
    volumes:
      - ./be/mcrcloundinary/mcrcloundinary:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    networks:
      - app-network

  gateway:
    build:
      context: ./be/getway/getway
    env_file:
      - ./be/getway/getway/.env
    container_name: getway
    ports:
      - "3001:3000"  # Container: 3000, Host: 3001
    environment:
      - PORT=3000
    volumes:
      - ./be/getway/getway:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_started
      user:
        condition: service_started
      product:
        condition: service_started
      cloundinary:
        condition: service_started
    networks:
      - app-network

  frontend:
    build: ./fe/shopquanao
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
      - WATCHPACK_IGNORE=**/{node_modules,.next,logs,dist,coverage}/**
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./fe/shopquanao:/app
      - /app/node_modules
    depends_on:
      gateway:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
