version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"     # Cổng AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  user:
    build: ./be/shopquanaobe
    env_file:
      - ./be/shopquanaobe/.env
    container_name: shopquanaobe
    ports:
      - "3004:3000"  # Container: 3000, Host: 3001
    volumes:
      - ./be/shopquanaobe:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  product:
    build: ./be/mcrproduct/mcrproduct
    env_file:
      - ./be/mcrproduct/mcrproduct/.env
    container_name: mcrproduct
    ports:
      - "3002:3000"
    volumes:
      - ./be/mcrproduct/mcrproduct:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  cloundinary:
    build:
      context: ./be/mcrcloundinary/mcrcloundinary
    env_file:
      - ./be/mcrcloundinary/mcrcloundinary/.env  # Nếu Dockerfile nằm sâu
    container_name: mcrcloundinary
    ports:
      - "3003:3000"
    volumes:
      - ./be/mcrcloundinary/mcrcloundinary:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  gateway:
    build:
      context: ./be/getway/getway
    env_file:
      - ./be/getway/getway/.env  # Nếu Dockerfile nằm sâu
    container_name: getway
    ports:
      - "3001:3000"
    volumes:
      - ./be/getway/getway:/app
      - /app/node_modules
    depends_on:
      - rabbitmq



  frontend:
    build: ./fe/shopquanao
    # dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./fe/shopquanao:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - cloundinary
      - product
      - user
      - gateway
